# default parameters taken from <link>

# Model parameters
out_dim: 65536
momentum_teacher: 0.996

# Temperature teacher parameters
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 30


# Training/Optimization parameters
epochs: 100
min_lr: 0.000001
warmup_epochs: 10
lr: 0.0005
weight_decay: 0.04
weight_decay_end: 0.4

batch_size_per_gpu: 64
local_crops_number: 8
clip_grad: 3.0
freeze_last_layer: 1

# Multi-crop parameters
global_crops_scale: [0.4, 1.]
local_crops_number: 8
local_crops_scale: [0.05, 0.4]



